# Generated by Django 4.2.18 on 2025-02-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
